apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: enterprise-dev
  labels:
    app: customer-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: customer-service

  template:
    metadata:
      labels:
        app: customer-service

    spec:
      containers:
        - name: customer-service
          image: customer-service:1.2.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: ENVIRONMENT
              value: "dev"

            - name: ORDER_SERVICE_URL
              value: "http://order-service:5001"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: enterprise-dev

spec:
  selector:
    app: customer-service

  ports:
    - port: 5000
      targetPort: 5000

  type: ClusterIP